### ISSUE TITLE
Handle Essay Answer In Submission Page

### ISSUE THREAD

**Issue by jauhararifin** [ia-toki/judgels#138]
Currently, raphael render contestant answer as it is. For essay problem, the answer might be a programming language code, and can be very long that cannot display the answer in the table cell. So maybe we can:
- Ellipsise the answer and use popup to display the whole answer.
- Use `<pre>` tag to render the answer.

And in problem page, maybe we can:
- Use code editor for submission?

**Comment by nathanchrs** [comment]
To do this, we also need to have the item types of each submission in the submissions list and contestant answers summary endpoints. I will add a `problemTypesMap` field in both endpoints.
