### ISSUE TITLE
Bundle contest UX problems

### ISSUE THREAD

**Issue by nathanchrs** [ia-toki/judgels#150]
This is a list of UX problems found related to bundle contests, especially for OSP Online 2019. Add problems in comments.

**Comment by nathanchrs** [comment]
- [x] In essay items, when the contestant has not answered yet, the answer textarea looks like it is enabled, but is actually read-only before the contestant presses the `Answer` button. This can be fixed by making it obvious when the textarea is read-only, e.g. by changing the background color to gray.

- [ ] In bundle submissions summary (per-contestant) view, the header showing the currently viewed username is too small - it is quite easy to miss.

**Comment by chidx** [comment]
> In essay items, when the contestant has not answered yet, the answer textarea looks like it is enabled, but is actually read-only before the contestant presses the Answer button. This can be fixed by making it obvious when the textarea is read-only, e.g. by changing the background color to gray.

Should it be applied to short items as well? @nathanchrs

**Comment by nathanchrs** [comment]
**Additional UX comments from others**
- For short answer/essay items, it might not be immediately obvious to contestants that they must click the `Answer` button before answering. Suggestion: add placeholder text for the textbox e.g. "klik tombol Answer untuk mengisi jawaban", or make clicking the disable textbox activate the textbox
- Suggestion: immediately set focus to the short answer/essay item textbox when clicking the `Answer` button
- Display the input format restriction (e.g. "jawaban hanya boleh terdiri dari angka") to the contestant. Suggestion: we can put the input format description in the problem statement manually as a workaround for now
- Make it clear to the contestant that he/she can still change the answer after clicking the `Submit` button. Suggestion: display a small help text
- Suggestion: use Indonesian for the UI text, as some contestants may not be comfortable with English
