### ISSUE TITLE
Consider not using code splitting at all

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#183]
So that onsite contests can "preload" whole bundle beforehand by opening the website in all contest PCs.

**Comment by nathanchrs** [comment]
I think we should still do code-splitting, but split code according to user roles instead (e.g. admin chunk is larger since it has TinyMCE)

**Comment by fushar** [comment]
Yes, need to think how to do it though, since administrative role functionalities are spread across tabs/pages.
