### ISSUE TITLE
Disable link to timeanddate if mode is PRIVATE_CONTESTS

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#186]
So that contestants wont mistakenly open a restricted domain in private contest setting

**Comment by jauhararifin** [comment]
Is this changes `uriel` too? `raphael` need information whether contest is private from `uriel`

**Comment by fushar** [comment]
No, this is just raphael config:

https://github.com/ia-toki/judgels/blob/master/judgels-frontends/raphael/src/conf.ts
