### ISSUE TITLE
Checkbox when editting test group shown incorrectly in Firefox

### ISSUE THREAD

**Issue by gyosh** [ia-toki/judgels#21]
After ticking some checkboxes in test group and update it, firefox won't show the mark in marked checkboxes. However that the server knows that it was ticked. So it is just displayed incorrectly.
It works in chrome.

**Comment by fushar** [comment]
What are the steps required to reproduce this bug?

**Comment by gyosh** [comment]
1. Open firefox
2. Open repository.ia-toki.org. Login if necessary
3. Create new problem, the problem-type is batchWithSubtask
4. Upload some files for the test data
5. Create 2 test group, assign some test data
6. Tick some checkboxes in each test group
7. Update the configuration
8. When the page reloads, witness that the ticks in checkboxes have gone. Copy the page URL
9. Now open chrome, open the copied URL
10. Witness that the ticks in checkboxes appeared
