### ISSUE TITLE
Document to run Jerahmeel service in Dev's Guide as well

### ISSUE THREAD

**Issue by jonathanirvings** [ia-toki/judgels#238]
Document to run Jerahmeel service in https://github.com/ia-toki/judgels/wiki/Dev's-Guide:-Running-from-source

**Comment by jonathanirvings** [comment]
It might be worth to have seed data for Jerahmeel as well, possibly including submissions.

**Comment by fushar** [comment]
This is done (docs + seeds containing submissions)

**Comment by jonathanirvings** [comment]
Thank you!
