### ISSUE TITLE
Problem not sorted correctly

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#247]
In https://tlx.toki.id/problems?archive=troc

it is better to have TROC 10 after TROC 9, not in between 1 and 2

**Comment by fushar** [comment]
This is hard to solve without special sorting mechanism (e.g. tokenization and sort in numerical ascending order if the token is a number).

Another possibility is to rename TROC to TROC 09.

**Comment by yonasadiel** [comment]
What if we disable the ordering-by-name for problems that are filtered by archive slug:

https://github.com/ia-toki/judgels/blob/a145c5fdb61917e3651214fc7b2e14b956013273/judgels-backends/jerahmeel/jerahmeel-app/src/main/java/judgels/jerahmeel/problemset/ProblemSetStore.java#L65-L67

Instead, we may use createdAt or updatedAt?

**Comment by fushar** [comment]
Cannot. What if I added an old contest archive?

**Comment by prabowo02** [comment]
Is it possible to manually order the problemsets?

For [Compfest archive](https://tlx.toki.id/problems?archive=compfest), every year they use different branding and it is almost impossible to sort by the name alone

**Comment by prabowo02** [comment]
is it possible if we add another field called "contestDate", which is the actual time the contest was held?
I think this might solve all our ordering problem, including compfest problemset
