### ISSUE TITLE
Bug in filtering supervisor's (and manager's) submissions

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#252]
In the submissions page, only some of the non-contestants' usernames are shown in the filter.

Example:
In [TROC 10 Testing Page 1](https://tlx.toki.id/contests/troc-10-testing/submissions), patrick is not shown in the user filter.
But in [Page 3](https://tlx.toki.id/contests/troc-10-testing/submissions?page=3), patrick is shown, but hocky is not shown.
In [Page 2](https://tlx.toki.id/contests/troc-10-testing/submissions?page=2), both patrick and hocky are not shown

**Comment by fushar** [comment]
User filter = set of contestants, union set of unique submission authors (maybe managers/supervisors) in that page.

This is expected. To remove confusion maybe we should only have user filter = set of contestants only.

**Comment by prabowo02** [comment]
Why not set of contestants union set of supervisors?

Sometimes supervisors may help testing the problem before the contest, and we want to filter those submissions

**Comment by fushar** [comment]
Ah, makes more sense. Let's do it!
