### ISSUE TITLE
Add new TROC contest style

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#257]
Similar to _GCJ style_, but with a few differences:

- Wrong submissions on Accepted problems will not be counted towards total penalty time.
- Dark green color on the scoreboard for first Accepted problems.

**Comment by prabowo02** [comment]
Also add these features for TLX style:

- Compile Error is not counted towards penalty
- Wrong answers on the samples are not counted towards penalty

**Comment by fushar** [comment]
I think this should be just called TROC style?

**Comment by fushar** [comment]
We have implemented this, except:

> Wrong answers on the samples are not counted towards penalty
