### ISSUE TITLE
Add editorial tab in contest menu

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#285]
This editorial tab will be immediately available after the contest ended

Contestants no longer have to wait for organizers to announce it (in CF announcement, or FB Olimp Info Group)

N.B. AtCoder has this feature too

**Comment by fushar** [comment]
Resolved via https://github.com/ia-toki/judgels/commit/d21df69b8d7fd1f466abd681a30bf3a31b27861b
