### ISSUE TITLE
[feature-request] download or copy solution in submission

### ISSUE THREAD

**Issue by freethought101** [ia-toki/judgels#287]
simple yet helpful feature to learners. we can see our solution, but when we copy it manually, it always add extra enter on every line. it seems trivial, but on a little longer code this can be hassle. e.g:

source:
int main(){
      return 0;
}
copy:

int main(){

      return 0;

}

**Comment by fushar** [comment]
I cannot reproduce it. Which browser are you using? Can you describe exact steps to reproduce this bug?

**Comment by prabowo02** [comment]
I was experiencing the same thing, where an extra line is added in between every line of code. But it seems the problem is no longer there for now.

**Comment by fushar** [comment]
Cool, closing it then. Feel free to reopen if this occurs again.
