### ISSUE TITLE
[Contest Module Request] Remove Penalty on First Sample and Compile Error

### ISSUE THREAD

**Issue by hockyy** [ia-toki/judgels#289]
![image](https://user-images.githubusercontent.com/19528709/84596298-0b340d00-ae87-11ea-95e5-479029e200a9.png)
Pada beberapa kontes TROC terakhir pula masih ada peserta yang tidak sengaja melakukan submiit dengan C++14, sehingga mengalami compile-error dan dihitung sebagai penalti.

**Comment by fushar** [comment]
Duplicate of https://github.com/ia-toki/judgels/issues/257.
