### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#291]
C++14 and Pypy

**Comment by zweimach** [comment]
Please also add support for Haskell, Rust, and JavaScript.
I know it is hard and these languages are not officially supported in OSN, IOI, and ACM ICPC, but other online judge sites support more languages including these.
At least adding more languages is worth trying.
And maybe we can attract more users to this awesome platform.

**Comment by fushar** [comment]
Added C++17 and PyPy!
