### ISSUE TITLE
Consider merging Jophiel & Sealtiel

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#293]
They are always deployed together in the same machine, why making them 2 separate services.

**Comment by dronjax** [comment]
Separation of concern? Sealtiel can be easily replaced using message queue service such as AWS SQS right?

**Comment by fushar** [comment]
> Sealtiel can be easily replaced using message queue service such as AWS SQS right?

In practice this won't happen. There is no requirement and there is no bandwidth to do this, so this is a non-existent issue.

**Comment by fushar** [comment]
Obsolete. We've killed Sealtiel via b8100c03e0ec79775ee4e3e6326d2fc831b338c5.
