### ISSUE TITLE
Create a read-only access for Partners

### ISSUE THREAD

**Issue by jonathanirvings** [ia-toki/judgels#294]
Currently, there is no way to give read-only access for partners for some section (e.g., there is a "Allowed to manage grading?" option, but there is no "Allowed to view grading?" option).

Consider adding an "Allowed to commit changes" option or similar, so we can give all access to partners but disabling the ability to commit, essentially giving a read-only access to all sections of the problem

**Comment by fushar** [comment]
This is done in v2. We only have 2 permission types: `VIEW` or `UPDATE`.

`VIEW` permission can only view, but not modify anything.

<img width="729" alt="image" src="https://github.com/ia-toki/judgels/assets/1525580/45b122ae-6181-430d-97e5-91f3c92650ab">
