### ISSUE TITLE
User Activity Log

### ISSUE THREAD

**Issue by dragoon20** [ia-toki/judgels#34]
Add user activity log support in Jophiel and provide API for other system to use it.
Example: User (dragoon20) has entered contest (Pelatnas 1) on Client (Uriel) from IP xxxx at time ....

**Comment by fushar** [comment]
Why don't we store the log at the individual components instead?

**Comment by dragoon20** [comment]
This feature is pending on the next milestone since it needs more time and gonna be missed on milestore 0.1.0.
