### ISSUE TITLE
Image dimensions when viewing source code does not fit

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#358]
<img width="500" alt="Screenshot 2021-01-19 at 9 48 51 PM" src="https://user-images.githubusercontent.com/18303489/105046920-a556d600-5aa4-11eb-99b3-9cb26ec8a307.png">
I think this is reproducible when you view a short source code, then view a long source code. All these actions must be done in the same tab

**Comment by azaky** [comment]
I could not replicate it by "viewing short code then long source code" method mentioned above.

However, I found a way to (so far, consistently) replicate it by the following:
1. open own submission page, i.e. where the submission is text, not image
2. then open other people's submission page. It should be distorted, whether it is a long or short one.

I think wrapping [this](https://github.com/ia-toki/judgels/blob/b1030052903cc269f5aba194b915828df5d20a75/judgels-frontends/raphael/src/components/SubmissionDetails/Programming/SubmissionDetails.jsx#L285) inside a `div.submission-image` will solve the problem (and as the side effect, it will make the image scrollable; I don't know whether it is a desired behavior).

Another way is to differentiate the `image-submission` class on the dialog and on the submission page.
