### ISSUE TITLE
Progress bar doesn't match sum of points

### ISSUE THREAD

**Issue by rama-pang** [ia-toki/judgels#359]
![image](https://user-images.githubusercontent.com/55415829/105063528-688fdc80-5aae-11eb-88bd-24fc312d573e.png)
![image](https://user-images.githubusercontent.com/55415829/105063548-6ded2700-5aae-11eb-85a9-e6b2712d788e.png)
The progress bar should be 700pts/7 instead of 600pts/7

**Comment by fushar** [comment]
Yeah, it is a known race condition issue when a user submits solutions to a new problemset too quickly between submissions in different problems.

For now I've manually fixed your data. Please check again.

This issue will remain open until this is resolved.

**Comment by fushar** [comment]
Offending exception:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'JIDUSERXCcE36qmrr8Tm46k3hSV-JIDPRSEQASaehflR7QgzE3mVIXx' for key 'jerahmeel_stats_user_problem_set.userJid_problemSetJid'
```
