### ISSUE TITLE
Progress bar doesn't match sum of points

### ISSUE THREAD

**Issue by rama-pang** [ia-toki/judgels#369]
![image](https://user-images.githubusercontent.com/55415829/107880642-b6afc880-6f12-11eb-8f89-c9ddcb3cb000.png)
![image](https://user-images.githubusercontent.com/55415829/107880648-be6f6d00-6f12-11eb-9731-2575669d5cba.png)

The progress bar should be 700pts/7 instead of 600pts/7.

**Comment by fushar** [comment]
:'( will investigate

**Comment by fushar** [comment]
Related to #359
