### ISSUE TITLE
Make sure problem and submission match

### ISSUE THREAD

**Issue by amnucode** [ia-toki/judgels#376]
Current behavior: It is possible to open link like this [https://tlx.toki.id/problems/apio-2020/B/submissions/783969](https://tlx.toki.id/problems/apio-2020/B/submissions/783969).

Explanation: Submission 783969 should be ini APIO 2015 problem A.

![image](https://user-images.githubusercontent.com/66343191/109407486-b6540a80-79b3-11eb-9348-d6d37d1ec418.png)

**Comment by FwP-IDN** [comment]
Additional: change problem slug to a valid problem slug and valid alias also possible

example: 

- https://tlx.toki.id/problems/troc-20/G/submissions/783969 --> valid
- https://tlx.toki.id/problems/troc-20/H/submissions/783969 --> not valid bcz troc-20 problem alias only A til G
