### ISSUE TITLE
Redirect loop when connecting to AWS's Jophiel from *.local

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#41]

**Comment by dragoon20** [comment]
Set cookie must be on the same domain or subdomain.
Ex: if sso is sso.ia-toki.org, then on local must be *.ia-toki.org to set cookie too.

TODO: Possible solution: when logout, deactivate the access token and refresh token.

**Comment by dragoon20** [comment]
Fixed in:
ia-toki/judgels-uriel@7f6caa6bdfa8d019667104b1e9f213b7a7189a89
ia-toki/judgels-sandalphon@387997fd3fc8e8be48e5ff0ebcb5950a975a8571
