### ISSUE TITLE
Support Python 3.9 or higher

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#416]
They provide some built-in functions that are useful for Competitive Programming.

Python 3.8

* `pow(x, -1, mod)` to compute modular inverses
* `math.prod()` to compute product of numbers
* `math.comb()` and `math.perm()` for combinatoric computations
* `math.isqrt()` to compute integer square root

Python 3.9

* `math.gcd()` with multiple arguments
* `math.lcm()` to compute least common multiple
* `graphlib.TopologicalSorted()` for toposort

And of course, they have improved overall performances as well

**Comment by fushar** [comment]
As of v2, the current version of Python is 3.10:

```
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
```
