### ISSUE TITLE
Bug in Courses Progress

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#420]
<img width="272" alt="Screenshot 2022-01-25 at 12 56 40 AM" src="https://user-images.githubusercontent.com/18303489/150828473-ffa8de87-ee01-4d60-95f3-8ad663c1a039.png">

I have completed all the problems of the courses from the screenshot above

**Comment by fushar** [comment]
Fixed via https://github.com/ia-toki/judgels/commit/489d718ea890f67e56ac7f54227fac3ec389a491.
