### ISSUE TITLE
Support "All Permissions" to Sandalphon Partners

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/judgels#421]
It's a bit inconvenient to tick all those permissions everytime a new partner need to be added.

Usually one contest may consists of > 5 problems, and there may be about 4-5 people involved with the problemset, which results in about 5*5*10=250 manual ticking operations

Possible solution is to either:
* On adding new partner, all permissions are checked by default
* Add a "all permissions" button (just like Contest Supervisors)

**Comment by fushar** [comment]
Maybe we can do the following:
- Supporting adding multiple partners at once (comma-separated), and
- All permissions are checked by default

**Comment by fushar** [comment]
The above have been implemented in Judgels v2!
