### ISSUE TITLE
After clicking "Regrade all" button in a contest, show loading state in the button

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#453]
<img width="384" alt="Screen Shot 2023-06-19 at 05 54 41" src="https://github.com/ia-toki/judgels/assets/1525580/c9131d53-7e05-4c9a-8e65-7de95b989136">

This is because the server can take quite a while to finish to regrade request, especially when the number of submissions is large.

**Comment by rwhendry** [comment]
Currently, we already have 3 confirmation alerts when clicking on regrade all pages button. Not sure if giving the loading state will give any benefits.

**Comment by fushar** [comment]
This is the reason:

> This is because the server can take quite a while to finish to regrade request, especially when the number of submissions is large.

The way regrade works is to send the submissions for grading to RabbitMQ, one-by-one (page-per-page):

https://github.com/ia-toki/judgels/blob/b5e8eae35d8f2b576715f6f41d95ab8da7850883/judgels-backends/judgels-server-app/src/main/java/judgels/uriel/contest/submission/programming/ContestSubmissionResource.java#L334

When there are hundreds of submissions, this can take a while (a few seconds), so a loading state is useful to give indication that something is running. Otherwise, the user can be tempted to click the button again, resulting in duplicate regrade requests.
