### ISSUE TITLE
Broken System Page

### ISSUE THREAD

**Issue by iqlal** [ia-toki/judgels#500]
Cannot view System Page on Superadmin Dashboard

![image](https://github.com/ia-toki/judgels/assets/64581779/4593c57a-e489-4260-9fa5-a4c6f8ea2bc3)

**Comment by fushar** [comment]
Halo @iqlal, boleh email saya di (username github saya) @ gmail, nanti saya add ke discord supaya lebih enak diskusinya. Terima kasih :)
