### ISSUE TITLE
[Development] Node.js Version 16 Required to Properly Run the judgels-client

### ISSUE THREAD

**Issue by kadeksuryam** [ia-toki/judgels#535]
Currently, when running the judgels-client with a Node.js version higher than 16, the application fails to start, resulting in the following errors:

![image](https://github.com/ia-toki/judgels/assets/21070615/83b66470-c967-49b6-a383-ac365e0ea043)

Therefore, in the Developer's Guide, it is essential to explicitly mention that Node.js version 16 should be used.

**Comment by fushar** [comment]
Rather than this, can we fix the problem so that judgels-client runs on Node > 16? 😄

**Comment by kadeksuryam** [comment]
Okay, I will try to find a way to fix that
