### ISSUE TITLE
Upgrade mysql-connector-java to 8.0.33

### ISSUE THREAD

**Issue by rizaon** [ia-toki/judgels#543]
Currently, judgels db user need to be created with `mysql_native_password` in MySQL 8.

```
CREATE USER 'judgels'@'%' IDENTIFIED WITH mysql_native_password BY 'judgels';
```

mysql 8 change its default authentication from mysql_native_password to caching_sha2_password.

https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password

Upgrading mysql-connector-java will allow seamless connection to the latest MySQL version without the need to set `WITH mysql_native_password` manually.

**Comment by fushar** [comment]
Related:

- #534

😄 cc: @kadeksuryam
