### ISSUE TITLE
Create version bumper script

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#66]
A script that when run in judgels, the correct tags will be created in all branches.

The spirit is to make release process just one-click.

For example:

`scripts/bump-version.sh v0.2.0`

**Comment by petrabarus** [comment]
While you into this, I think it would be awesome if you could show the release version (or commit version) in the site footer

**Comment by fushar** [comment]
Nice idea. Just created a new issue for that (#69).

**Comment by fushar** [comment]
This is not finished yet. A version bumper script should be able to update the versions in build.sbt files. (E.g., if we bump version 0.4.0, all versions in all build.sbt files should become 0.4.0.)

**Comment by dragoon20** [comment]
I think, you should relook at the code, all build.sbt files are also updated
