### ISSUE TITLE
Does versioning apply to the whole Judgels, or to each of its applications?

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#68]
For example, can we have Sandalphon 2.0 (for example, with cool problem translation feature) along with Sealtiel 1.0? Or do we want to just call the whole as Judgels 2.0?

**Comment by dragoon20** [comment]
Yeah, I think we should use different version for each application as they progress

**Comment by petrabarus** [comment]
When you have a dedicated person maintaining the progress of each application it's okay to have different versions for each applications.

But since you are pretty much undermanned, just use same version for all.

**Comment by fushar** [comment]
I also agree that we should be using the same version all. This makes creating documentation and Javadoc much easier.

**Comment by fushar** [comment]
@dragoon20 has agreed.
