### ISSUE TITLE
Support MathJax in problem statements

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#7]
See the problem Hello World:

<img width="353" alt="screenshot 2018-08-20 18 00 38" src="https://user-images.githubusercontent.com/1525580/44336860-f5c84480-a4a2-11e8-99d8-45a25f669518.png">

The equation should be rendered properly.

**Comment by jauhararifin** [comment]
why dont we implement this like this: https://engineering.classpro.in/render-latex-in-react-using-mathjax-f9742504678

**Comment by fushar** [comment]
1) It involves hitting CDN (external URL). Judgels should be able to be self-hosted.
2) If we want to host the JS files ourselves, the files are quite large. Haven't invested time to investigate which files are really required to show equations.

**Comment by lungsin** [comment]
This article might help:
https://github.com/mathjax/MathJax/wiki/Understanding-mathjax-performance
