### ISSUE TITLE
Petra's Question

### ISSUE THREAD

**Issue by dragoon20** [ia-toki/judgels#77]
1. Berapa lama Instance gak ada terus ke production?
2. Berapa lama deploy versi terbaru?
3. Berapa banyak bisa dipotong?

**Comment by petrabarus** [comment]
what's the update on this?

**Comment by dragoon20** [comment]
about this:
1. How long new instance creation takes? From what i test is about 5 - 7 minutes to start new instance from existing AMI?
2. How long to deploy new version?
   - pull from github takes at most 1 minute.
   - publishing app into jar and so on about 3 minutes.
   - context switch from existing app into new at most 1 minute.
3. How much time can be cut?
   I don't really know about which part can be cut. But based on the status I tried to deploy more than one instance of grader and sso and use ELB.
