### ISSUE TITLE
baselayout.scala.html pageTitle unused

### ISSUE THREAD

**Issue by alijaya** [ia-toki/judgels#89]
@(pageTitle: String)(content: Html)

the pageTitle is unused...

**Comment by fushar** [comment]
Hmm? See line 7.

**Comment by dragoon20** [comment]
So, I guess this issues is not a problem. Thanks.

**Comment by alijaya** [comment]
@fushar : hmmm? in line 7 there's nothing... ._., it's just whitespace...

**Comment by fushar** [comment]
@alijaya https://github.com/ia-toki/judgels-play-commons/blob/master/app/org/iatoki/judgels/commons/views/layouts/baseLayout.scala.html#L7

**Comment by alijaya** [comment]
lho... ._.
I think I pull the wrong version ._.
in my local... it's not like that... :v... ok... my bad :v...
