### ISSUE TITLE
Submission lefts are incorrectly shown on contestant's problem list

### ISSUE THREAD

**Issue by fushar** [ia-toki/judgels#9]
To reproduce:

- Add a problem in a contest, with some positive number of submission limits.
- Submit a solution for that problem.
- View the list of problems as contestants.
- Submissions left for that problem won't decrease.

**Comment by dragoon20** [comment]
Fixed in commit:
- play commons 8c409748415ca222999b62b89d23043610f5beb3
- uriel a38c3876b1524fc866d59b2dfad069cad41ce7cf
