### ISSUE TITLE
Sandalphon returns HTTP 500 when requesting problem and the current user does not have permission for the problem

### ISSUE THREAD

**Issue by nathanchrs** [ia-toki/judgels#91]
## Steps to reproduce
From Uriel, login as a user that does not have permission to access a certain problem in Sandalphon, then try to add that problem to a contest. The operation will fail because Sandalphon returns HTTP 500 instead of just returning a map of problems accessible by the current user.

See:
- https://github.com/ia-toki/judgels/blob/master/judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/problem/ContestProblemResource.java#L76
- https://github.com/ia-toki/judgels/blob/master/judgels-legacy/sandalphon/app/org/iatoki/judgels/sandalphon/controllers/api/client/v2/ClientProblemAPIControllerV2.java#L176

**Comment by fushar** [comment]
Hmm I just tested on integration. It returns 403 correctly. Please double check?

**Comment by fushar** [comment]
This is due to wrong sandalphon client credentials setting in Uriel's config file. So 500 is actually correct as the server is incorrectly set up.
